### ISSUE TITLE
Problem signing up

### ISSUE THREAD

**Issue by lightningRalf** [NimbleBoxAI/ChainFury#89]
After signing up, I return to the login page. With out any hint if it was successful or that I would receive an email.

When I try to sign in with the credentials I signed up with I get an 'invalid credentials' comment.

I didnt receive any email.
Email should have been sent to *@skiff.com
Maybe this is the problem?

> Demo site is up and running now.
> Sign up- 
> [https://chainfury.nbox.ai/ui/signup](https://chainfury.nbox.ai/ui/signup)
> 
> _Originally posted by @chanh-1 in > https://github.com/NimbleBoxAI/ChainFury/issues/72#issuecomment-1518538328_

**Comment by vgulerianb** [comment]
If you are being redirected to the login page after signing up, it indicates that your account has been successfully created. Please attempt to log in again using your username (not email) and password.
